dataset:
  name: generic
  tag: generic_config
  img_size: 128
model:
  name: dti_sprites
  n_sprites: 40
  n_backgrounds: 1
  n_objects: 1
  inject_noise: 0.
  encoder_name: resnet18
  prototype:
    source: data
    data:
      freeze: [False, False, False]
      value: [0.1, 0.5, 0.]
      init: ["constant", "mean", "gaussian"]
      gaussian_weights_std: 25
  transformation_sequence: color_projective
  transformation_sequence_bkg: color_projective
  curriculum_learning: False
  curriculum_learning_bkg: False
  input_alpha_as_weight: True
training:
  batch_size: 32
  n_workers: 5
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [700]
  n_epoches: 400
  train_stat_interval: 1000
  val_stat_interval: 2000
  check_cluster_interval: 250
  seed: 32903
  visualizer_port:
  pretrained:
  resume:
